### ISSUE TITLE
There are parts of theme that doesn't see well

### ISSUE THREAD

**Issue by mesteryui** [catppuccin/vendetta#25]
Here are screenshots of those parts:
![Screenshot_20240102-090439_Vendetta](https://github.com/catppuccin/vendetta/assets/108957859/b7e2828c-3b81-43fb-8a0b-5567da048a1d)
![Screenshot_20240102-090505_Vendetta](https://github.com/catppuccin/vendetta/assets/108957859/f3a5543d-e049-4233-94e7-93aa0e2d632b)

**Comment by riivx** [comment]
i hope i can look more into fixing new layout when i get access to it (i love discord)

**Comment by mesteryui** [comment]
And also this
![Screenshot_20240102-184818_Vendetta](https://github.com/catppuccin/vendetta/assets/108957859/a17efb55-2fea-46b6-a2ab-7c6ec62152bd)

**Comment by Quinxxxx** [comment]
> Here are screenshots of those parts: ![Screenshot_20240102-090439_Vendetta](https://private-user-images.githubusercontent.com/108957859/293649113-b7e2828c-3b81-43fb-8a0b-5567da048a1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTA5NzQsIm5iZiI6MTcwNDM5MDY3NCwicGF0aCI6Ii8xMDg5NTc4NTkvMjkzNjQ5MTEzLWI3ZTI4MjhjLTNiODEtNDNmYi04YTBiLTU1NjdkYTA0OGExZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxNzUxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Nzg3YTYxMjI2NDU0OTYxOWM0MmY4MzA2MDAyOTdkZDA3YjlmMTk3YWZlNTQyNTNlYjY4ZDFiNWFlNTM4YWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jo5E-ha4uQlSvHK6Jp-yR1xsw2WNBsUzCJ6M8pkGbxM) ![Screenshot_20240102-090505_Vendetta](https://private-user-images.githubusercontent.com/108957859/293649151-f3a5543d-e049-4233-94e7-93aa0e2d632b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTA5NzQsIm5iZiI6MTcwNDM5MDY3NCwicGF0aCI6Ii8xMDg5NTc4NTkvMjkzNjQ5MTUxLWYzYTU1NDNkLWUwNDktNDIzMy05NGU3LTkzYWEwZTJkNjMyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxNzUxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjM2ZWMwMjc2Yzk1MGYwYWZlNDUzOGMwNDM4NWNjN2YyYTE5NmE0M2M3Njg2MWZkMGQ4NmUyYTVkNDQwZjc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.reYIYhy0I08oAxuqYlwhfQX_TFkisDnNfbDoMrqS7QE)

Which parts are you on about exactly?? If you're on the about the server name text in channels list and nitro text in you page then they're themed by WHITE_500 afaik so changing them will cause disgusting contrast issues in a lot of places

**Comment by mesteryui** [comment]
I don't know but that doesn't look good it would be good if you can do anything

**Comment by Quinxxxx** [comment]
No can do sorry. Blame discord for this terrible use of strings 😭

**Comment by Rairof** [comment]
Afaik, its doable now

**Comment by Different-Name** [comment]
The latte theme is quite broken - I suspect all themes are affected by this, but it is quite evident on the latte theme 
![Screenshot_20240620_112457_edited_1718850319886969](https://github.com/catppuccin/vendetta/assets/49257026/3b8c5bde-d85e-46b8-a703-33f20f7935f6)
