### ISSUE TITLE
Migration from Vendetta to another compatible Client-Mod

### ISSUE THREAD

**Issue by TGRush** [catppuccin/vendetta#26]
If you've been following the previous developer of Vendetta, or checked their GitHub repositories, you may know that Vendetta is now End-Of-Life. More information here: https://maisy.moe

Regardless, this means that this theme needs to be either:
- Discontinued
- Updated (in the future) to support another compatible client-mod, e.g [Revenge](https://github.com/revenge-mod/Revenge) or [Bunny](https://github.com/pyoncord/Bunny)

As such, this issue serves as a hub for discussion regarding a potential move, discontinuation, or other measures.

**Comment by rubyowo** [comment]
I mean really we can still keep the repo up with a very clear warning that Vendetta is EOL and they should switch to another client

**Comment by riivx** [comment]
Making EOL notice and mentioning both of the forks is the best option

**Comment by riivx** [comment]
I personally like Revenge more, because it already has custom fonts support

**Comment by riivx** [comment]
But yeah, I'll include the warning, thanks
