### ISSUE TITLE
Add option that removes the font

### ISSUE THREAD

**Issue by resucutie** [catppuccin/vendetta#29]
Due to Revenge having support for custom fonts which you can't disable, it is reasonable to give the option to disable fonts, as some people aren't so welcoming about them not being able to revert the font without changing the theme entirely

**Comment by riivx** [comment]
the only way to do so is to create separate themes without fonts
but i think revenge might add a way to disable fonts

**Comment by Rairof** [comment]
Pyoncord* and soon.tm

**Comment by riichi67** [comment]
after discussing it, we decided it's better to drop the fonts support as it's not in the catppuccin's theming guidelines
